name: Fusebit - Publish
on:
  create:
    tags:
      - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Load dependencies
        run: make deps
      - name: Build docker container
        run: make build-docker-full
